# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ex1_config = debug
  ex2_config = debug
  texturing_config = debug
  modelviewer_config = debug
  grass_config = debug
  sphereworld_color_config = debug
  flying_config = debug
  glm_modelviewer_config = debug
  glm_texturing_config = debug
  point_sprites_config = debug
  glm_sphereworld_color_config = debug
  glm_grass_config = debug
  glm_flying_config = debug
  left_handed_config = debug
  gears_config = debug
endif
ifeq ($(config),release)
  ex1_config = release
  ex2_config = release
  texturing_config = release
  modelviewer_config = release
  grass_config = release
  sphereworld_color_config = release
  flying_config = release
  glm_modelviewer_config = release
  glm_texturing_config = release
  point_sprites_config = release
  glm_sphereworld_color_config = release
  glm_grass_config = release
  glm_flying_config = release
  left_handed_config = release
  gears_config = release
endif

PROJECTS := ex1 ex2 texturing modelviewer grass sphereworld_color flying glm_modelviewer glm_texturing point_sprites glm_sphereworld_color glm_grass glm_flying left_handed gears

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ex1:
ifneq (,$(ex1_config))
	@echo "==== Building ex1 ($(ex1_config)) ===="
	@${MAKE} --no-print-directory -C build -f ex1.make config=$(ex1_config)
endif

ex2:
ifneq (,$(ex2_config))
	@echo "==== Building ex2 ($(ex2_config)) ===="
	@${MAKE} --no-print-directory -C build -f ex2.make config=$(ex2_config)
endif

texturing:
ifneq (,$(texturing_config))
	@echo "==== Building texturing ($(texturing_config)) ===="
	@${MAKE} --no-print-directory -C build -f texturing.make config=$(texturing_config)
endif

modelviewer:
ifneq (,$(modelviewer_config))
	@echo "==== Building modelviewer ($(modelviewer_config)) ===="
	@${MAKE} --no-print-directory -C build -f modelviewer.make config=$(modelviewer_config)
endif

grass:
ifneq (,$(grass_config))
	@echo "==== Building grass ($(grass_config)) ===="
	@${MAKE} --no-print-directory -C build -f grass.make config=$(grass_config)
endif

sphereworld_color:
ifneq (,$(sphereworld_color_config))
	@echo "==== Building sphereworld_color ($(sphereworld_color_config)) ===="
	@${MAKE} --no-print-directory -C build -f sphereworld_color.make config=$(sphereworld_color_config)
endif

flying:
ifneq (,$(flying_config))
	@echo "==== Building flying ($(flying_config)) ===="
	@${MAKE} --no-print-directory -C build -f flying.make config=$(flying_config)
endif

glm_modelviewer:
ifneq (,$(glm_modelviewer_config))
	@echo "==== Building glm_modelviewer ($(glm_modelviewer_config)) ===="
	@${MAKE} --no-print-directory -C build -f glm_modelviewer.make config=$(glm_modelviewer_config)
endif

glm_texturing:
ifneq (,$(glm_texturing_config))
	@echo "==== Building glm_texturing ($(glm_texturing_config)) ===="
	@${MAKE} --no-print-directory -C build -f glm_texturing.make config=$(glm_texturing_config)
endif

point_sprites:
ifneq (,$(point_sprites_config))
	@echo "==== Building point_sprites ($(point_sprites_config)) ===="
	@${MAKE} --no-print-directory -C build -f point_sprites.make config=$(point_sprites_config)
endif

glm_sphereworld_color:
ifneq (,$(glm_sphereworld_color_config))
	@echo "==== Building glm_sphereworld_color ($(glm_sphereworld_color_config)) ===="
	@${MAKE} --no-print-directory -C build -f glm_sphereworld_color.make config=$(glm_sphereworld_color_config)
endif

glm_grass:
ifneq (,$(glm_grass_config))
	@echo "==== Building glm_grass ($(glm_grass_config)) ===="
	@${MAKE} --no-print-directory -C build -f glm_grass.make config=$(glm_grass_config)
endif

glm_flying:
ifneq (,$(glm_flying_config))
	@echo "==== Building glm_flying ($(glm_flying_config)) ===="
	@${MAKE} --no-print-directory -C build -f glm_flying.make config=$(glm_flying_config)
endif

left_handed:
ifneq (,$(left_handed_config))
	@echo "==== Building left_handed ($(left_handed_config)) ===="
	@${MAKE} --no-print-directory -C build -f left_handed.make config=$(left_handed_config)
endif

gears:
ifneq (,$(gears_config))
	@echo "==== Building gears ($(gears_config)) ===="
	@${MAKE} --no-print-directory -C build -f gears.make config=$(gears_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f ex1.make clean
	@${MAKE} --no-print-directory -C build -f ex2.make clean
	@${MAKE} --no-print-directory -C build -f texturing.make clean
	@${MAKE} --no-print-directory -C build -f modelviewer.make clean
	@${MAKE} --no-print-directory -C build -f grass.make clean
	@${MAKE} --no-print-directory -C build -f sphereworld_color.make clean
	@${MAKE} --no-print-directory -C build -f flying.make clean
	@${MAKE} --no-print-directory -C build -f glm_modelviewer.make clean
	@${MAKE} --no-print-directory -C build -f glm_texturing.make clean
	@${MAKE} --no-print-directory -C build -f point_sprites.make clean
	@${MAKE} --no-print-directory -C build -f glm_sphereworld_color.make clean
	@${MAKE} --no-print-directory -C build -f glm_grass.make clean
	@${MAKE} --no-print-directory -C build -f glm_flying.make clean
	@${MAKE} --no-print-directory -C build -f left_handed.make clean
	@${MAKE} --no-print-directory -C build -f gears.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ex1"
	@echo "   ex2"
	@echo "   texturing"
	@echo "   modelviewer"
	@echo "   grass"
	@echo "   sphereworld_color"
	@echo "   flying"
	@echo "   glm_modelviewer"
	@echo "   glm_texturing"
	@echo "   point_sprites"
	@echo "   glm_sphereworld_color"
	@echo "   glm_grass"
	@echo "   glm_flying"
	@echo "   left_handed"
	@echo "   gears"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"